name: Block Private Branch Merge to 'main' branch from 'closed-source' branch

on:
    pull_request:
        branches:
            - main # Target branch is main

jobs:
    block-private-merge:
        runs-on: ubuntu-latest
        steps:
            - name: Check Source Branch
              run: |
                  if [[ "${{ github.head_ref }}" == "closed-source" ]]; then
                    echo "Merge from closed-source branch is not allowed!"
                    exit 1
                  fi
